[package]
name = "benchmarks"
version = "0.1.0"
authors = ["Adolfo Ochagavía <aochagavia92@gmail.com>"]

[dependencies.frontend]
path = "../frontend"

[dependencies.type_checker]
path = "../type_checker"

[dependencies]
time = "*"
